apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaler
  namespace: eda-streams
  labels:
    scaledobject.keda.sh/name: kafka-consumer-scaler
spec:
  cooldownPeriod: 60
  maxReplicaCount: 30
  minReplicaCount: 1
  pollingInterval: 5
  scaleTargetRef:
    name: reporting-consumer-deployment
  triggers:
    - type: prometheus 
      metadata:
        metricName: kafka_consumergroup_lag
        namespace: eda-streams
        query: 'sum(kafka_consumergroup_lag{topic="my-topic",consumergroup="report-group"})'
        serverAddress: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9092'
        threshold: '100'
        authModes: "bearer"
      authenticationRef:
        name: keda-trigger-auth-prometheus
